services:
  chat:
    container_name: live-chat
    restart: always
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - cassandra
    environment:
      GRPC_CLIENT_SOMETHING_ADDRESS: static://manager-backend:9000
      SPRING_CASSANDRA_CONTACT-POINTS: cassandra-chat
    ports:
      - "8090:8090"
      - "9000:9000"
    networks:
      - live-shopping-network


  cassandra:
    image: cassandra:latest
    container_name: cassandra-chat
    ports:
      - "9042:9042"
    networks:
      - live-shopping-network


      
  init-db:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      - cassandra
    entrypoint: ["/cassandra-spring.sh"]
    volumes:
      - ./cassandra-spring.sh:/cassandra-spring.sh
    networks:
      - live-shopping-network


networks:
  live-shopping-network:
    name: live-shopping-network
    external: true

