services:
  manager-native:
    container_name: manager-backend
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-native}
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-manager:5433/postgres
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres-manager:5433/postgres
    ports:
      - "8080:8080"
    networks:
      - live-shopping-network

  postgres:
    image: postgres:16.2
    container_name: postgres-manager
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager
      PGPORT: 5433
    ports:
      - "5433:5433"
    networks:
      - live-shopping-network


networks:
  live-shopping-network:
    name: live-shopping-network
